# Generated by Django 4.1.9 on 2023-06-24 08:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="dateOfBirth",
            field=models.DateField(blank=True, null=True),
        ),
    ]
