# Generated by Django 4.1.9 on 2023-06-24 18:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_userprofile_dateofbirth"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="Users",
        ),
        migrations.AlterModelTable(
            name="userprofile",
            table="UserProfile",
        ),
    ]
