# Generated by Django 4.2.2 on 2023-07-05 16:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_table_alter_userprofile_table"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="jobGroup",
            field=models.CharField(default="A", max_length=20),
        ),
    ]
