# Generated by Django 4.1.9 on 2023-06-24 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("request", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="imprestrequest",
            name="action_taken_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="imprest_actions",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="imprestrequest",
            name="imprest_amount",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
