# Generated by Django 4.1.9 on 2023-06-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0003_leaverequest"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[("yearly", "Yearly Leave"), ("sick", "Sick Leave"), ("commuted", "Commuted Leave")],
                default="yearly",
                max_length=20,
            ),
        ),
    ]
