# Generated by Django 4.1.9 on 2023-06-24 18:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0009_alter_imprestrequest_table_alter_leaverequest_table"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="leaverequest",
            name="leave_start_before_end",
        ),
    ]
