# Generated by Django 4.1.9 on 2023-06-24 19:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0010_remove_leaverequest_leave_start_before_end"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="duration",
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("day_off", "Day Off"),
                    ("yearly", "Yearly Leave"),
                    ("sick", "Sick Leave"),
                    ("commuted", "Commuted Leave"),
                ],
                default="yearly",
                max_length=20,
            ),
        ),
    ]
