# Generated by Django 4.1.9 on 2023-06-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0011_alter_leaverequest_duration_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="leaverequest",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
