# Generated by Django 4.1.9 on 2023-06-24 19:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0012_alter_leaverequest_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="duration",
            field=models.IntegerField(default=1, null=True),
        ),
    ]
