# Generated by Django 4.1.9 on 2023-06-24 20:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0013_alter_leaverequest_duration"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="duration",
            field=models.IntegerField(default=1),
        ),
    ]
