# Generated by Django 4.2.2 on 2023-06-26 20:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0015_leavecredit_leaverequest_leave_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="imprestrequest",
            name="action_count",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="imprestrequest",
            name="monitoring",
            field=models.CharField(
                choices=[
                    ("initiated", "Initiated"),
                    ("first_action", "First Action"),
                    ("second_action", "Second Action"),
                    ("third_action", "Third Action"),
                ],
                default="initiated",
                max_length=20,
            ),
        ),
    ]
