# Generated by Django 4.2.2 on 2023-06-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0017_remove_leaverequest_leave_credit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="custom_duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="duration",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(default="", max_length=200),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="start_date",
            field=models.DateField(default=None, null=True),
        ),
    ]
