# Generated by Django 4.2.2 on 2023-06-27 12:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0018_alter_leaverequest_custom_duration_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="leaverequest",
            name="end_date",
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
