# Generated by Django 4.2.2 on 2023-07-06 10:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("request", "0019_alter_leaverequest_end_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="imprestrequest",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="created_at",
            field=models.DateTimeField(db_index=True, default=datetime.datetime.now),
        ),
    ]
