# Generated by Django 4.2.2 on 2023-06-27 12:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("cards", "0003_jobcard_user_alter_jobcategory_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobcard",
            name="job_category",
            field=models.CharField(
                choices=[("support", "Support"), ("design", "Design"), ("project", "Project"), ("usual", "Usual")],
                default="usual",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="jobcard",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="created_job_cards",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="JobCategory",
        ),
    ]
