# Generated by Django 4.2.2 on 2023-07-06 10:59

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(db_index=True, default=datetime.datetime.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "event",
                    models.CharField(
                        choices=[
                            ("leave_created", "Leave Request Created"),
                            ("ticket_status_change", "Ticket Status Change"),
                            ("job_card_escalated", "Job Card Escalated"),
                        ],
                        max_length=50,
                    ),
                ),
                ("content", models.TextField()),
                ("priority", models.PositiveIntegerField(blank=True, default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                        ],
                        default="created",
                        max_length=20,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                (
                    "content_type",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="contenttypes.contenttype"),
                ),
                (
                    "recipient",
                    models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["recipient"], name="notificatio_recipie_be3f1a_idx"),
                    models.Index(fields=["created_at"], name="notificatio_created_46ad24_idx"),
                ],
            },
        ),
    ]
