# Generated by Django 4.2.2 on 2023-07-06 11:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="notification",
            new_name="Notificatio_recipie_7a7cd4_idx",
            old_name="notificatio_recipie_be3f1a_idx",
        ),
        migrations.RenameIndex(
            model_name="notification",
            new_name="Notificatio_created_e9230d_idx",
            old_name="notificatio_created_46ad24_idx",
        ),
        migrations.AlterModelTable(
            name="notification",
            table="Notifications",
        ),
    ]
