# Generated by Django 4.2.3 on 2023-07-07 11:10

import datetime
from django.db import migrations
import fnm.common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_rename_notificatio_recipie_be3f1a_idx_notificatio_recipie_7a7cd4_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="created_at",
            field=fnm.common.fields.DateTimeTzField(
                default=datetime.datetime(2023, 7, 7, 11, 10, 38, 784967, tzinfo=datetime.timezone.utc),
                editable=False,
                verbose_name="update_at",
            ),
        ),
        migrations.AlterField(
            model_name="notification",
            name="updated_at",
            field=fnm.common.fields.DateTimeTzField(
                default=datetime.datetime(2023, 7, 7, 11, 10, 38, 785033, tzinfo=datetime.timezone.utc),
                editable=False,
                verbose_name="update_at",
            ),
        ),
    ]
